Redund_Code = '''
for i in range(24):
    robot.drive_wheels(100,-100)
    robot.set_backpack_lights(cozmo.lights.off_light,cozmo.lights.green_light,cozmo.lights.blue_light,cozmo.lights.green_light,cozmo.lights.off_light)
    cube1.set_light_corners(cozmo.lights.green_light, cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.blue_light)
    cube2.set_light_corners(cozmo.lights.green_light, cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.blue_light)
    cube3.set_light_corners(cozmo.lights.green_light, cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.blue_light)
    time.sleep(.1)
    robot.set_backpack_lights(cozmo.lights.off_light,cozmo.lights.blue_light,cozmo.lights.green_light,cozmo.lights.blue_light,cozmo.lights.off_light)
    cube1.set_light_corners(cozmo.lights.blue_light, cozmo.lights.green_light, cozmo.lights.blue_light, cozmo.lights.blue_light)
    cube2.set_light_corners(cozmo.lights.blue_light, cozmo.lights.green_light, cozmo.lights.blue_light, cozmo.lights.blue_light)
    cube3.set_light_corners(cozmo.lights.blue_light, cozmo.lights.green_light, cozmo.lights.blue_light, cozmo.lights.blue_light)
    time.sleep(.1)
    robot.set_backpack_lights(cozmo.lights.off_light,cozmo.lights.green_light,cozmo.lights.blue_light,cozmo.lights.green_light,cozmo.lights.off_light)
    cube1.set_light_corners(cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.green_light, cozmo.lights.blue_light)
    cube2.set_light_corners(cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.green_light, cozmo.lights.blue_light)
    cube3.set_light_corners(cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.green_light, cozmo.lights.blue_light)
    time.sleep(.1)
    robot.set_backpack_lights(cozmo.lights.off_light,cozmo.lights.blue_light,cozmo.lights.green_light,cozmo.lights.blue_light,cozmo.lights.off_light)
    cube1.set_light_corners(cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.green_light)
    cube2.set_light_corners(cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.green_light)
    cube3.set_light_corners(cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.blue_light, cozmo.lights.green_light)
    time.sleep(.1)
    robot.set_backpack_lights(cozmo.lights.off_light,cozmo.lights.green_light,cozmo.lights.red_light,cozmo.lights.green_light,cozmo.lights.off_light)
    cube1.set_light_corners(cozmo.lights.red_light, cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.green_light)
    cube2.set_light_corners(cozmo.lights.red_light, cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.green_light)
    cube3.set_light_corners(cozmo.lights.red_light, cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.green_light)
    time.sleep(.1)
    robot.set_backpack_lights(cozmo.lights.off_light,cozmo.lights.red_light,cozmo.lights.green_light,cozmo.lights.red_light,cozmo.lights.off_light)
    cube1.set_light_corners(cozmo.lights.green_light, cozmo.lights.red_light, cozmo.lights.green_light, cozmo.lights.green_light)
    cube2.set_light_corners(cozmo.lights.green_light, cozmo.lights.red_light, cozmo.lights.green_light, cozmo.lights.green_light)
    cube3.set_light_corners(cozmo.lights.green_light, cozmo.lights.red_light, cozmo.lights.green_light, cozmo.lights.green_light)
    time.sleep(.1)
    robot.set_backpack_lights(cozmo.lights.off_light,cozmo.lights.green_light,cozmo.lights.red_light,cozmo.lights.green_light,cozmo.lights.off_light)
    cube1.set_light_corners(cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.red_light, cozmo.lights.green_light)
    cube2.set_light_corners(cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.red_light, cozmo.lights.green_light)
    cube3.set_light_corners(cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.red_light, cozmo.lights.green_light)
    time.sleep(.1)
    robot.set_backpack_lights(cozmo.lights.off_light,cozmo.lights.red_light,cozmo.lights.green_light,cozmo.lights.red_light,cozmo.lights.off_light)
    cube1.set_light_corners(cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.red_light)
    cube2.set_light_corners(cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.red_light)
    cube3.set_light_corners(cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.green_light, cozmo.lights.red_light)
    time.sleep(.1)
'''
Cozmo_Says1 = (" i picked up power cube 1, I will place it on top of power cube 2")
Cozmo_Says2 = ("i placed power cube 1 on top of power cube 2")
Cozmo_Says3 = ("i picked up power cube 3, to place it beside the other 2 power cubes")
Cozmo_Says4 = ("i placed power cube 3 beside the other 2 power cubes")
Cozmo_Says4 = ("i picked up power cube 1 again, i will place it on top of power cube 3")
Cozmo_Says5 = ("i placed power cube 1 on top of power cube 3")
Cozmo_Says6 = ("yeah, i did it")
Cozmo_Says7 = ("anim_poked_giggle")

import cozmo
import time
def cozmo_program(robot: cozmo.robot.Robot):
        from cozmo.objects import LightCube1Id, LightCube2Id, LightCube3Id
        from cozmo.util import degrees, Pose, distance_mm, speed_mmps

        robot.set_head_angle(degrees(0.0)).wait_for_completed()
        robot.set_lift_height(0.0).wait_for_completed()
        cube1 = robot.world.get_light_cube(LightCube1Id)
        cube2 = robot.world.get_light_cube(LightCube2Id)
        cube3 = robot.world.get_light_cube(LightCube3Id)
        robot.set_all_backpack_lights(cozmo.lights.white_light)

        cube1.set_lights(cozmo.lights.white_light)
        cube2.set_lights(cozmo.lights.white_light)
        cube3.set_lights(cozmo.lights.white_light)

        lookaround = robot.start_behavior(cozmo.behavior.BehaviorTypes.LookAroundInPlace) 
        robot.world.wait_until_observe_num_objects(num=3, object_type=cozmo.objects.LightCube, timeout=60)
        lookaround.stop()

        robot.set_all_backpack_lights(cozmo.lights.blue_light)
        cube1.set_lights(cozmo.lights.blue_light)
        cube2.set_lights(cozmo.lights.blue_light)
        cube3.set_lights(cozmo.lights.blue_light)

        robot.pickup_object(cube1,use_pre_dock_pose=True, in_parallel=True, num_retries=5).wait_for_completed()
        robot.set_all_backpack_lights(cozmo.lights.green_light.flash())
        cube1.set_lights(cozmo.lights.green_light.flash())

        robot.say_text(Cozmo_Says1, play_excited_animation=False,use_cozmo_voice=False,duration_scalar=1.0,voice_pitch=0.0).wait_for_completed()
        robot.place_on_object(cube2,use_pre_dock_pose=True, in_parallel=True, num_retries=5).wait_for_completed()
        robot.set_all_backpack_lights(cozmo.lights.blue_light)
        cube1.set_lights(cozmo.lights.green_light)
        cube2.set_lights(cozmo.lights.green_light)

        robot.say_text(Cozmo_Says2, play_excited_animation=False,use_cozmo_voice=False,duration_scalar=1.0,voice_pitch=0.0).wait_for_completed()
        robot.pickup_object(cube3,use_pre_dock_pose=True, in_parallel=True, num_retries=5).wait_for_completed()
        robot.set_all_backpack_lights(cozmo.lights.green_light.flash())
        cube3.set_lights(cozmo.lights.green_light.flash())

        robot.say_text(Cozmo_Says3, play_excited_animation=False,use_cozmo_voice=False,duration_scalar=1.0,voice_pitch=0.0).wait_for_completed()
        robot.place_on_object(cube2,use_pre_dock_pose=True, in_parallel=True, num_retries=5).wait_for_completed()
        robot.set_all_backpack_lights(cozmo.lights.blue_light)
        cube3.set_lights(cozmo.lights.green_light)
        robot.place_object_on_ground_here(cube3, num_retries=5).wait_for_completed()
        robot.go_to_object(cube3, distance_mm(3.0)).wait_for_completed()
        robot.drive_straight(distance_mm(-50), speed_mmps(50)).wait_for_completed()

        robot.say_text(Cozmo_Says4, play_excited_animation=False,use_cozmo_voice=False,duration_scalar=1.0,voice_pitch=0.0).wait_for_completed()
        robot.pickup_object(cube1,use_pre_dock_pose=True, in_parallel=True, num_retries=5).wait_for_completed() 
        robot.set_all_backpack_lights(cozmo.lights.red_light.flash())
        cube1.set_lights(cozmo.lights.red_light.flash())
        cube2.set_lights(cozmo.lights.red_light)

        robot.say_text(Cozmo_Says4, play_excited_animation=False,use_cozmo_voice=False,duration_scalar=1.0,voice_pitch=0.0).wait_for_completed()
        robot.place_on_object(cube3,use_pre_dock_pose=True, in_parallel=True, num_retries=5).wait_for_completed()
        robot.set_all_backpack_lights(cozmo.lights.blue_light)
        cube1.set_lights(cozmo.lights.red_light)
        cube3.set_lights(cozmo.lights.red_light)

        robot.say_text(Cozmo_Says5, play_excited_animation=False,use_cozmo_voice=False,duration_scalar=1.0,voice_pitch=0.0).wait_for_completed()
        robot.set_all_backpack_lights(cozmo.lights.white_light)
        cube1.set_lights(cozmo.lights.white_light)
        cube2.set_lights(cozmo.lights.white_light)
        cube3.set_lights(cozmo.lights.white_light)

        robot.say_text(Cozmo_Says6, play_excited_animation=True,use_cozmo_voice=True,duration_scalar=1.0,voice_pitch=0.0).wait_for_completed()
        robot.play_anim(name= Cozmo_Says7).wait_for_completed()
        robot.drive_straight(distance_mm(-50), speed_mmps(50)).wait_for_completed()
        anim = robot.play_anim_trigger(cozmo.anim.Triggers.AudioTestAnim)
        exec(Redund_Code)
cozmo.run_program(cozmo_program, use_viewer=True)

# robot.drive_straight(distance_mm(420), speed_mmps(50)).wait_for_completed()
